"""
subtitle_service.py — Subtitle extraction, parsing, slicing, and burning.

Features:
- Parses WebVTT (.vtt) and SubRip (.srt) files downloaded by yt-dlp
- Handles auto-generated YouTube captions (cleaning HTML/cue tags)
- Slices and re-times subtitles for each individual video clip (00:00:00 relative)
- Formats TikTok / Shorts / Reels style captions (yellow text, black outline, bottom center)
- Builds FFmpeg subtitles filter with proper character escaping
"""
import re
from pathlib import Path
from utils.logger import get_logger

logger = get_logger(__name__)


class SubtitleService:
    @staticmethod
    def find_and_parse_subtitles(directory: Path, base_stem: str = "_download_temp") -> list[dict]:
        """
        Looks for any subtitle file generated by yt-dlp in `directory`
        (e.g., `_download_temp.pt.vtt`, `_download_temp.en.srt`, etc.)
        and returns a list of cues: [{'start': float, 'end': float, 'text': str}].
        """
        if not directory.exists():
            return []

        # Find any matching subtitle files
        sub_files = []
        for ext in (".vtt", ".srt"):
            sub_files.extend(list(directory.glob(f"{base_stem}*{ext}")))

        if not sub_files:
            logger.info(f"No subtitle files found for {base_stem} in {directory}")
            return []

        # Prefer Portuguese, then any file
        sub_files.sort(key=lambda p: (0 if ".pt" in p.name.lower() else 1, p.stat().st_size), reverse=False)
        target_file = sub_files[0]
        logger.info(f"Found subtitle file: {target_file.name} ({target_file.stat().st_size} bytes)")

        try:
            content = target_file.read_text(encoding="utf-8", errors="ignore")
            if target_file.suffix.lower() == ".vtt":
                return SubtitleService._parse_vtt(content)
            else:
                return SubtitleService._parse_srt(content)
        except Exception as e:
            logger.error(f"Failed to read/parse subtitle file {target_file}: {e}")
            return []

    @staticmethod
    def _parse_vtt(content: str) -> list[dict]:
        cues = []
        # Match WebVTT timestamps: 00:01:23.456 --> 00:01:26.789 or 01:23.456 --> 01:26.789
        time_re = re.compile(r'(?:(\d+):)?(\d{2}):(\d{2})[\.,](\d{3})\s*-->\s*(?:(\d+):)?(\d{2}):(\d{2})[\.,](\d{3})')
        tag_re = re.compile(r'<[^>]+>')

        blocks = re.split(r'\n\s*\n', content.strip())
        for block in blocks:
            lines = [l.strip() for l in block.splitlines() if l.strip()]
            time_idx = -1
            for i, l in enumerate(lines):
                if '-->' in l:
                    time_idx = i
                    break
            if time_idx == -1:
                continue

            m = time_re.search(lines[time_idx])
            if not m:
                continue

            sh1, sm1, ss1, sms1, eh1, em1, es1, ems1 = m.groups()
            start_sec = int(sh1 or 0) * 3600 + int(sm1) * 60 + int(ss1) + int(sms1) / 1000.0
            end_sec = int(eh1 or 0) * 3600 + int(em1) * 60 + int(es1) + int(ems1) / 1000.0

            raw_text = ' '.join(lines[time_idx + 1:])
            clean_text = tag_re.sub('', raw_text).strip()
            # Clean repeated spaces
            clean_text = re.sub(r'\s+', ' ', clean_text)

            if clean_text and end_sec > start_sec:
                # Avoid duplicate identical text if YouTube sent duplicate rolling lines
                if cues and cues[-1]['text'] == clean_text and abs(cues[-1]['end'] - start_sec) < 0.3:
                    cues[-1]['end'] = max(cues[-1]['end'], end_sec)
                else:
                    cues.append({'start': start_sec, 'end': end_sec, 'text': clean_text})
        return cues

    @staticmethod
    def _parse_srt(content: str) -> list[dict]:
        cues = []
        time_re = re.compile(r'(\d{2}):(\d{2}):(\d{2})[\.,](\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})[\.,](\d{3})')
        tag_re = re.compile(r'<[^>]+>')

        blocks = re.split(r'\n\s*\n', content.strip())
        for block in blocks:
            lines = [l.strip() for l in block.splitlines() if l.strip()]
            time_idx = -1
            for i, l in enumerate(lines):
                if '-->' in l:
                    time_idx = i
                    break
            if time_idx == -1:
                continue

            m = time_re.search(lines[time_idx])
            if not m:
                continue

            sh, sm, ss, sms, eh, em, es, ems = m.groups()
            start_sec = int(sh) * 3600 + int(sm) * 60 + int(ss) + int(sms) / 1000.0
            end_sec = int(eh) * 3600 + int(em) * 60 + int(es) + int(ems) / 1000.0

            raw_text = ' '.join(lines[time_idx + 1:])
            clean_text = tag_re.sub('', raw_text).strip()
            clean_text = re.sub(r'\s+', ' ', clean_text)

            if clean_text and end_sec > start_sec:
                cues.append({'start': start_sec, 'end': end_sec, 'text': clean_text})
        return cues

    @staticmethod
    def slice_cues_to_srt(cues: list[dict], clip_start: float, clip_end: float,
                           output_srt_path: Path, words_per_line: int = 5) -> bool:
        """
        Filters cues overlapping [clip_start, clip_end], shifts timestamps
        to be relative to clip_start (00:00:00 start), and saves to `output_srt_path`.
        Returns True if any subtitles were written.
        """
        duration = clip_end - clip_start
        sliced = []

        for c in cues:
            if c['end'] <= clip_start or c['start'] >= clip_end:
                continue

            rel_start = max(0.0, c['start'] - clip_start)
            rel_end = min(duration, c['end'] - clip_start)

            if rel_end > rel_start + 0.1:
                # Wrap long text into short lines for vertical screens
                text = SubtitleService._format_caption_text(c['text'], words_per_line)
                sliced.append({
                    'start': rel_start,
                    'end': rel_end,
                    'text': text
                })

        if not sliced:
            return False

        lines = []
        for i, cue in enumerate(sliced, 1):
            lines.append(str(i))
            lines.append(f"{SubtitleService._format_time(cue['start'])} --> {SubtitleService._format_time(cue['end'])}")
            lines.append(cue['text'])
            lines.append("")

        output_srt_path.write_text("\n".join(lines), encoding="utf-8")
        return True

    @staticmethod
    def _format_caption_text(text: str, words_per_line: int = 5) -> str:
        words = text.split()
        if len(words) <= words_per_line:
            return text
        chunks = []
        for i in range(0, len(words), words_per_line):
            chunks.append(" ".join(words[i:i + words_per_line]))
        return "\n".join(chunks)

    @staticmethod
    def _format_time(sec: float) -> str:
        total_ms = int(round(sec * 1000))
        s, ms = divmod(total_ms, 1000)
        m, s = divmod(s, 60)
        h, m = divmod(m, 60)
        return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

    @staticmethod
    def build_ffmpeg_subtitles_filter(srt_path: str, format: str = '9:16',
                                       font_size: int = 28, position: str = 'bottom') -> str:
        """
        Builds the FFmpeg subtitle filter with high-contrast, viral-style styling:
        - Bold font
        - Vibrant yellow text (&H0000FFFF) with sharp black outline
        - Properly positioned above platform UI (TikTok / Shorts / Reels)
        """
        # Escape path for FFmpeg filter argument
        escaped_path = srt_path.replace('\\', '/').replace(':', r'\:').replace("'", r"\'")

        # Alignment in SSA/ASS subtitle style:
        # 2 = Bottom-Center, 10 = Mid-Center, 6 = Top-Center
        if position == 'top':
            alignment = 6
            margin_v = 100
        elif position == 'center':
            alignment = 10
            margin_v = 0
        else:  # default 'bottom'
            alignment = 2
            margin_v = 140  # Above TikTok caption & audio bar

        # High-contrast TikTok yellow captions:
        # PrimaryColour=&H0000FFFF (Yellow in BGR format)
        # OutlineColour=&H00000000 (Black outline)
        # BorderStyle=1 (Outline + drop shadow)
        style = (
            f"Fontname=Arial,"
            f"FontSize={font_size},"
            f"Bold=1,"
            f"PrimaryColour=&H0000FFFF,"
            f"OutlineColour=&H00000000,"
            f"BackColour=&H80000000,"
            f"BorderStyle=1,"
            f"Outline=3,"
            f"Shadow=1,"
            f"Alignment={alignment},"
            f"MarginV={margin_v}"
        )

        return f"subtitles='{escaped_path}':force_style='{style}'"
